### ISSUE TITLE
Support for external internalization

### ISSUE THREAD

**Issue by ledoyen** [jhorstmann/zuchini#22]
Another feature not included in Gherkin, is an extension point for users to define their own translation of the EN Gherkin language without the need to commit the master file `gherkin-languages.json`.

Is translation to other languages something planned ?

**Comment by jhorstmann** [comment]
Hi, this is not something that is planned at the moment. In my experience code and corresponding tests are nearly always in English, even if written by non-native speakers. I might reconsider if you can give me some examples of projects currently using internationalized scenarios with cucumber.

**Comment by jhorstmann** [comment]
Closing for now, but please reopen if there is a good usecase
