### ISSUE TITLE
After hooks should run also for failed scenarios

### ISSUE THREAD

**Issue by jhorstmann** [jhorstmann/zuchini#29]
https://github.com/cucumber/cucumber/wiki/Hooks#scenario-hooks

> `After` hooks will be run after the last step of each scenario, even when there are failing, undefined, pending or skipped steps.

 - What happens if one of the `After` hooks throws an exception? Are remaining hooks still executed?
 - What if a `Before` hook throws an exception?

**Comment by lukasniemeier-zalando** [comment]
I'd emulate the behavior of cucumber-jvm on `After` hooks. I hope they do execute all hooks regardless of someone throwing

**Comment by jhorstmann** [comment]
Fixed by #35
