### ISSUE TITLE
Support other build systems in zuchini-intellij-support

### ISSUE THREAD

**Issue by lukasniemeier-zalando** [jhorstmann/zuchini#31]
Currently `ZuchiniMain` of zuchini-intellij-support assumes a Maven style default build folder structure (see [here](https://github.com/jhorstmann/zuchini/blob/master/zuchini-intellij-support/src/main/java/org/zuchini/intellij/ZuchiniMain.java#L61). This does not work with other build systems like Gradle.

Default paths on Gradle look like:

```
~/my-project/out/test/resources/hello.feature
```

which does not match

```
~/my-project/src/test/resources/hello.feature
```
and the replacement String `/target/test-classes/` is not effective. Mind that the source set name `test` is just a convention and might be different for other projects.

**Comment by jhorstmann** [comment]
Running a single scenario also does not work anymore. Seems in recent IntelliJ versions the name filter was changed to use an anchored regex: https://github.com/JetBrains/intellij-plugins/commit/2884bf7fc3e27fc486b0b4a291b4cc6bf5ea720a

**Comment by lukasniemeier-zalando** [comment]
I've just noticed that after #33 IntelliJ *always* marks a scenario as **SUCESS** when started from within the IDE, regardless of the outcome.

![image](https://user-images.githubusercontent.com/10497901/33078386-cb50d628-ced2-11e7-8891-5c5df7177d40.png)

**Comment by lukasniemeier-zalando** [comment]
Seems to be a `NullPointerException`

```
    @Override
    public void testFailure(Failure failure) throws Exception {
        Description description = failure.getDescription();
        String timestamp = getCurrentTime();
        failure.getException().printStackTrace();

        StepInfo step = description.getAnnotation(StepInfo.class);
        if (step != null) {
            printf(TEMPLATE_TEST_FAILED, timestamp, "", escape(failure.getMessage()), step.name(), "error = 'true'");
        } else {
            ScenarioInfo scenario = description.getAnnotation(ScenarioInfo.class);
            printf(TEMPLATE_TEST_FAILED, timestamp, "", escape(failure.getMessage()), scenario.name(), "error = 'true'");
        }
    }
```
