### ISSUE TITLE
Inaccessible Type DatatableMatcher

### ISSUE THREAD

**Issue by lukasniemeier-zalando** [jhorstmann/zuchini#44]
The public API `DatatableMatchers#matchesTable` exposes package private type `DatatableMatcher`.

https://github.com/jhorstmann/zuchini/blob/bec38f61871976408d563d9fc5317b7e12568674/zuchini-runner/src/main/java/org/zuchini/runner/tables/DatatableMatchers.java#L8

This leads to problem in kotlin type inference. Should we expose `DatatableMatcher`?

**Comment by whiskeysierra** [comment]
Can't we just change the return type to `Matcher<Datatable>`?

**Comment by whiskeysierra** [comment]
It's actually interesting that Java has no issue with this. I can use it no problem, but I won't be able to assign it to a variable of that type. Not unlike an anonymous class.
